trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GLOBAL_SECRET: $(secretName)

steps:
- script: echo Hello, azure pipelines!
  displayName: 'Run a one-line script'

- bash: |
    echo "does this show? $MY_SECRET_NAME"
    echo "does this show? $GLOBAL_SECRET"
    echo "does this show? $MY_SECRET_VALUE"
    echo "does this show? $(MY_SECRET_VALUE)"
    go run ./bin/main.go
  env:
    MY_SECRET_NAME: $(secretName)
    MY_SECRET_VALUE: $(secretValue)
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables