trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, azure pipelines!
  displayName: 'Run a one-line script'

- script: |
    echo "does this show? $SECRET_NAME"
    echo "does this show? $SECRET_VALUE"
    go run main.go
  workingDirectory: '$(System.DefaultWorkingDirectory)/bin'
  displayName: 'Run script'
  env:
    SECRET_NAME: $(SECRET_NAME)
    SECRET_VALUE: $(SECRET_VALUE)
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables